[2021-01-28 18:47:23][debug][error]:[SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at file:/var/www/html/platform/vendor/easyswoole/orm/src/Db/MysqlPool.php line:22]
[2021-01-28 18:48:01][debug][error]:[SQLSTATE[42000] [1049] Unknown database 'platfoem' at file:/var/www/html/platform/vendor/easyswoole/orm/src/Db/MysqlPool.php line:22]
[2021-01-28 18:48:14][debug][error]:[SQLSTATE[22007] [1292] Incorrect datetime value: '1611830894' for column 'create_at' at row 1 [INSERT  INTO `user` (`create_at`, `update_at`)  VALUES (1611830894, 1611830894)] at file:/var/www/html/platform/vendor/easyswoole/orm/src/Db/MysqliClient.php line:78]
[2021-01-28 18:58:30][debug][error]:[Declaration of App\HttpModel\User\UserModel::schemaInfo(bool $isCache = true): Swoole\Table must be compatible with EasySwoole\ORM\AbstractModel::schemaInfo(bool $isCache = true): EasySwoole\ORM\Utility\Schema\Table at file:/var/www/html/platform/App/HttpModel/User/UserModel.php line:7]
